# Generated by Django 4.0.1 on 2022-01-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
