# Generated by Django 4.0.1 on 2022-01-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book1',
        ),
    ]
