# Generated by Django 4.0.1 on 2022-01-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_delete_book1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.BooleanField(),
        ),
    ]
